version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: moot-redis
    networks:
      - agent-network
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: moot-postgres
    environment:
      POSTGRES_DB: moot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - agent-network

  php-fpm:
    build: ./php-fpm
    container_name: moot-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "5173:5173"
    depends_on:
      - postgres
      - redis
    networks:
      - agent-network

  webserver:
    image: nginx:alpine
    container_name: moot-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  postgres-data:
